# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: list artifacts
        if: ${{ matrix.java == '21' }}
        id: list-artifacts
        run: |
          echo "::set-output name=files::$(ls -1 build/libs/ | jq -R -s -c 'split("\n") | map(select(length > 0))')"

      - name: capture build artifacts individually
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/libs/${{ matrix.artifact }}
        strategy:
          matrix:
            artifact: ${{ fromJson(steps.list-artifacts.outputs.files) }}
